#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirement
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.2/g ~/hosts.new
echo “facebook.com” > /etc/hosts
cp -f ~/hosts.new /etc/hosts
